name: CD K8s

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      # Set up kubectl
      - name: Set up Kubernetes
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}

      - name: Apply file yaml
        run: |
          sudo kubectl apply -f persistentVolume.yaml 
          sudo kubectl apply -f secret.yaml 
          sudo kubectl apply -f configMap.yaml 
          sudo kubectl apply -f service.yaml 
          sudo kubectl apply -f deployment.yaml 

      - name: Wait for all Pods to be Running
        run: |
          for i in {1..60}; do
            if sudo kubectl get pods --all-namespaces | grep -v Running | grep -v Completed; then
              echo "Waiting for pods to be in Running state..."
              sudo kubectl get all
              sleep 10
            else
              echo "All pods are in Running state."
              sudo kubectl get all
              break
            fi
          done

      - name: Check resources
        run: |
          sudo kubectl get all
